# Generated by Django 5.2 on 2025-04-07 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackingdata",
            name="time_zone",
        ),
    ]
