# Generated by Django 5.2 on 2025-04-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_remove_trackingdata_time_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="street_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
