# Generated by Django 5.2 on 2025-04-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_agent_city_agent_country_agent_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="notifications",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
