repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: .venv/bin/black
        language: system
        types: [python]
        args: ["apps"]
      - id: isort
        name: isort
        entry: .venv/bin/isort
        language: system
        types: [python]
        args: ["--profile", "black", "apps"]
      - id: flake8
        name: flake8
        entry: .venv/bin/flake8
        language: system
        types: [python]
        args: ["apps"]
      - id: mypy
        name: mypy
        entry: .venv/bin/mypy
        language: system
        types: [python]
        pass_filenames: false
        args: ["apps"]
      - id: bandit
        name: bandit
        entry: .venv/bin/bandit
        language: system
        types: [python]
        args: ["-r", "apps"]
