# Dockerfile.node
FROM node:18-alpine













# Set working directory
WORKDIR /app
COPY ./frontend/package*.json ./
RUN npm ci --legacy-peer-deps




# Copy source code
COPY frontend/ ./



EXPOSE 5173



# Copy entrypoint script
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]