version: "3.9"

services:
    ebcli:
        build:
            context: .
            dockerfile: Dockerfile.ebcli
        volumes:
            - .:/app
            - ~/.aws:/root/.aws:ro  # Read-only for AWS credentials (recommended)
        working_dir: /app
        entrypoint: eb
