# Generated by Django 5.2 on 2025-04-14 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "publishing_type",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("landing_page_url", models.URLField(blank=True, null=True)),
                ("tracking_pixel", models.TextField(blank=True, null=True)),
                ("ip_tracking", models.JSONField(blank=True, default=list, null=True)),
                (
                    "location_tracking",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "locale_tracking",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "time_tracking",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "browser_tracking",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="delivery.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="tracking.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("http_method", models.CharField(max_length=10)),
                ("server_timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("ip_data", models.JSONField(blank=True, null=True)),
                ("user_agent", models.TextField()),
                ("user_agent_data", models.JSONField(blank=True, null=True)),
                ("tracking_data", models.JSONField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking",
                        to="tracking.agent",
                    ),
                ),
            ],
        ),
    ]
