# Generated by Django 5.2.4 on 2025-12-16 08:22

import django.db.models.deletion

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageRequestData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("http_method", models.CharField(max_length=10)),
                ("server_timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "ip_source",
                    models.CharField(
                        blank=True,
                        choices=[("server", "Server"), ("client", "Header")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("os", models.CharField(blank=True, max_length=100, null=True)),
                ("browser", models.CharField(blank=True, max_length=100, null=True)),
                ("platform", models.CharField(blank=True, max_length=100, null=True)),
                ("locale", models.CharField(blank=True, max_length=10, null=True)),
                ("client_time", models.DateTimeField(blank=True, null=True)),
                (
                    "client_timezone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "location_source",
                    models.CharField(
                        blank=True,
                        choices=[("server", "Server"), ("client", "Header")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "_ip_data",
                    models.JSONField(blank=True, db_column="ip_data", null=True),
                ),
                (
                    "_user_agent_data",
                    models.JSONField(blank=True, db_column="user_agent_data", null=True),
                ),
                (
                    "_header_data",
                    models.JSONField(blank=True, db_column="header_data ", null=True),
                ),
                (
                    "_form_data",
                    models.JSONField(blank=True, db_column="form_data", null=True),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[("tracking", "Tracking"), ("review", "Review")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image to extract EXIF data",
                        null=True,
                        upload_to="exif_images/%Y/%m/%d/",
                    ),
                ),
                (
                    "altitude",
                    models.FloatField(
                        blank=True,
                        help_text="Altitude from EXIF GPS data (in meters)",
                        null=True,
                    ),
                ),
                (
                    "make",
                    models.CharField(
                        blank=True,
                        help_text="Camera/device manufacturer",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="Camera/device model",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "software",
                    models.CharField(
                        blank=True,
                        help_text="Software used to create/edit image",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "width",
                    models.IntegerField(blank=True, help_text="Image width in pixels", null=True),
                ),
                (
                    "height",
                    models.IntegerField(blank=True, help_text="Image height in pixels", null=True),
                ),
                (
                    "orientation",
                    models.IntegerField(blank=True, help_text="Image orientation (1-8)", null=True),
                ),
                (
                    "datetime_original",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when image was taken (from EXIF)",
                        null=True,
                    ),
                ),
                (
                    "datetime_digitized",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when image was digitized (from EXIF)",
                        null=True,
                    ),
                ),
                (
                    "exposure_time",
                    models.CharField(
                        blank=True,
                        help_text="Exposure time (e.g., '1/125')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "f_number",
                    models.FloatField(blank=True, help_text="F-number (aperture)", null=True),
                ),
                (
                    "iso_speed",
                    models.IntegerField(blank=True, help_text="ISO speed rating", null=True),
                ),
                (
                    "focal_length",
                    models.FloatField(blank=True, help_text="Focal length (in mm)", null=True),
                ),
                (
                    "flash",
                    models.BooleanField(blank=True, help_text="Flash fired", null=True),
                ),
                (
                    "raw_exif_data",
                    models.JSONField(
                        blank=True,
                        help_text="Complete raw EXIF data as JSON",
                        null=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_request_data",
                        to="tracking.token",
                    ),
                ),
                (
                    "tracking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_request_data",
                        to="tracking.tracking",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Image Request Data",
            },
        ),
        migrations.CreateModel(
            name="ImageData",
            fields=[],
            options={
                "verbose_name_plural": "Image Data",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tracking.imagerequestdata",),
        ),
        migrations.DeleteModel(
            name="ExifData",
        ),
        migrations.AddIndex(
            model_name="imagerequestdata",
            index=models.Index(
                fields=["data_type", "tracking"], name="tracking_im_data_ty_d99c06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagerequestdata",
            index=models.Index(
                fields=["data_type", "token"], name="tracking_im_data_ty_e651aa_idx"
            ),
        ),
        migrations.CreateModel(
            name="ExifData",
            fields=[],
            options={
                "verbose_name_plural": "EXIF Data",
                "ordering": ["-created_on"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tracking.imagerequestdata",),
        ),
    ]
