# Generated by Django 5.2.4 on 2025-11-08 04:37

import django.db.models.deletion

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterceptionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("http_method", models.CharField(max_length=10)),
                ("server_timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "ip_source",
                    models.CharField(
                        blank=True,
                        choices=[("server", "Server"), ("client", "Header")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("os", models.CharField(blank=True, max_length=100, null=True)),
                ("browser", models.CharField(blank=True, max_length=100, null=True)),
                ("platform", models.CharField(blank=True, max_length=100, null=True)),
                ("locale", models.CharField(blank=True, max_length=10, null=True)),
                ("client_time", models.DateTimeField(blank=True, null=True)),
                (
                    "client_timezone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "location_source",
                    models.CharField(
                        blank=True,
                        choices=[("server", "Server"), ("client", "Header")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "_ip_data",
                    models.JSONField(blank=True, db_column="ip_data", null=True),
                ),
                (
                    "_user_agent_data",
                    models.JSONField(blank=True, db_column="user_agent_data", null=True),
                ),
                (
                    "_header_data",
                    models.JSONField(blank=True, db_column="header_data ", null=True),
                ),
                (
                    "_form_data",
                    models.JSONField(blank=True, db_column="form_data", null=True),
                ),
                ("recipient_name", models.CharField(max_length=255)),
                ("street_address_line_1", models.CharField(max_length=255)),
                (
                    "street_address_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                (
                    "state_province",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                (
                    "_address_data",
                    models.JSONField(blank=True, db_column="address_data", null=True),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interception",
                        to="tracking.agent",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Interception Data",
            },
        ),
        migrations.CreateModel(
            name="NotificationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("http_method", models.CharField(max_length=10)),
                ("server_timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "ip_source",
                    models.CharField(
                        blank=True,
                        choices=[("server", "Server"), ("client", "Header")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("os", models.CharField(blank=True, max_length=100, null=True)),
                ("browser", models.CharField(blank=True, max_length=100, null=True)),
                ("platform", models.CharField(blank=True, max_length=100, null=True)),
                ("locale", models.CharField(blank=True, max_length=10, null=True)),
                ("client_time", models.DateTimeField(blank=True, null=True)),
                (
                    "client_timezone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "location_source",
                    models.CharField(
                        blank=True,
                        choices=[("server", "Server"), ("client", "Header")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "_ip_data",
                    models.JSONField(blank=True, db_column="ip_data", null=True),
                ),
                (
                    "_user_agent_data",
                    models.JSONField(blank=True, db_column="user_agent_data", null=True),
                ),
                (
                    "_header_data",
                    models.JSONField(blank=True, db_column="header_data ", null=True),
                ),
                (
                    "_form_data",
                    models.JSONField(blank=True, db_column="form_data", null=True),
                ),
                (
                    "_phone_data",
                    models.JSONField(blank=True, db_column="phone_data", null=True),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification",
                        to="tracking.agent",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notification Data",
            },
        ),
    ]
