# Generated by Django 5.2 on 2025-05-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agent",
            options={"verbose_name_plural": "Agents"},
        ),
        migrations.AlterModelOptions(
            name="campaign",
            options={"verbose_name_plural": "Campaigns"},
        ),
        migrations.AlterModelOptions(
            name="trackingdata",
            options={"verbose_name_plural": "Tracking Data"},
        ),
    ]
