# Generated by Django 5.2 on 2025-04-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackingdata",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="trackingdata",
            name="user_agent",
        ),
        migrations.AddField(
            model_name="trackingdata",
            name="headers_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
