# Generated by Django 5.2 on 2025-04-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_remove_trackingdata_ip_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackingdata",
            name="form_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
