# Generated by Django 5.2 on 2025-04-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0003_trackingdata_form_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="browser_precedence",
            field=models.CharField(
                choices=[("server", "Server"), ("client", "Client")],
                default="server",
                help_text="Determines whether to use server or client browser information for tracking",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="ip_precedence",
            field=models.CharField(
                choices=[("server", "Server"), ("client", "Client")],
                default="server",
                help_text="Determines whether to use server or client IP for tracking",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="locale_precedence",
            field=models.CharField(
                choices=[("server", "Server"), ("client", "Client")],
                default="server",
                help_text="Determines whether to use server or client locale for tracking",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="location_precedence",
            field=models.CharField(
                choices=[("server", "Server"), ("client", "Client")],
                default="server",
                help_text="Determines whether to use server or client location for tracking",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="time_precedence",
            field=models.CharField(
                choices=[("server", "Server"), ("client", "Client")],
                default="server",
                help_text="Determines whether to use server or client time for tracking",
                max_length=10,
            ),
        ),
    ]
