# Generated by Django 5.2 on 2025-04-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tracking",
            "0004_campaign_browser_precedence_campaign_ip_precedence_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="trackingdata",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackingdata",
            name="ip_source",
            field=models.CharField(
                blank=True,
                choices=[("server", "Server"), ("client", "Client")],
                max_length=10,
                null=True,
            ),
        ),
    ]
