# Generated by Django 5.2 on 2025-04-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0005_trackingdata_ip_address_trackingdata_ip_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackingdata",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackingdata",
            name="user_agent_source",
            field=models.CharField(
                blank=True,
                choices=[("server", "Server"), ("client", "Client")],
                max_length=10,
                null=True,
            ),
        ),
    ]
