# Generated by Django 5.2 on 2025-04-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0006_trackingdata_user_agent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackingdata",
            name="locale",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="trackingdata",
            name="locale_source",
            field=models.CharField(
                blank=True,
                choices=[("server", "Server"), ("client", "Client")],
                max_length=10,
                null=True,
            ),
        ),
    ]
