# Generated by Django 5.2 on 2025-04-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0007_trackingdata_locale_trackingdata_locale_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackingdata",
            name="client_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackingdata",
            name="client_timezone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trackingdata",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackingdata",
            name="location_source",
            field=models.CharField(
                blank=True,
                choices=[("server", "Server"), ("client", "Client")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trackingdata",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackingdata",
            name="time_source",
            field=models.CharField(
                blank=True,
                choices=[("server", "Server"), ("client", "Client")],
                max_length=10,
                null=True,
            ),
        ),
    ]
