# Generated by Django 5.2 on 2025-04-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0008_trackingdata_client_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackingdata",
            name="time_source",
        ),
        migrations.RemoveField(
            model_name="trackingdata",
            name="user_agent",
        ),
        migrations.RemoveField(
            model_name="trackingdata",
            name="user_agent_source",
        ),
        migrations.AddField(
            model_name="trackingdata",
            name="browser",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trackingdata",
            name="os",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trackingdata",
            name="platform",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
