# Generated by Django 5.2 on 2025-04-24 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0009_remove_trackingdata_time_source_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackingdata",
            name="locale_source",
        ),
    ]
