# Generated by Django 5.2 on 2025-04-25 15:20

import tracking.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0010_remove_trackingdata_locale_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="browser_precedence",
            field=models.CharField(
                choices=[("server", "Server"), ("client", "Header")],
                default=tracking.common.TrackingType["SERVER"],
                help_text="Determines whether to use server or client browser information for tracking",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="ip_precedence",
            field=models.CharField(
                choices=[("server", "Server"), ("client", "Header")],
                default=tracking.common.TrackingType["SERVER"],
                help_text="Determines whether to use server or client IP for tracking",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="locale_precedence",
            field=models.CharField(
                choices=[("server", "Server"), ("client", "Header")],
                default=tracking.common.TrackingType["SERVER"],
                help_text="Determines whether to use server or client locale for tracking",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="location_precedence",
            field=models.CharField(
                choices=[("server", "Server"), ("client", "Header")],
                default=tracking.common.TrackingType["SERVER"],
                help_text="Determines whether to use server or client location for tracking",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="time_precedence",
            field=models.CharField(
                choices=[("server", "Server"), ("client", "Header")],
                default=tracking.common.TrackingType["SERVER"],
                help_text="Determines whether to use server or client time for tracking",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="trackingdata",
            name="ip_source",
            field=models.CharField(
                blank=True,
                choices=[("server", "Server"), ("client", "Header")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="trackingdata",
            name="location_source",
            field=models.CharField(
                blank=True,
                choices=[("server", "Server"), ("client", "Header")],
                max_length=10,
                null=True,
            ),
        ),
    ]
